# Generated by Django 3.0.3 on 2020-06-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200605_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
